custom_domains = {
    "proxy": [
        "animelist.ir",
    ],
    "direct": [
        "upera.tv",
        "mashadkala.com",
        "persiangig.com",
        "livetabco.com",
        "arvancdn.com",
        "cedarmaps.com",
        "digikalacloud.com",
        "ebidar.com",
        "farsimode.com",
        "glorytoon.com",
        "iranserver.com",
        "ketaabonline.com",
        "ketab.io",
        "maryamsoft.com",
        "mindupmarket.com",
        "mipersia.com",
        "nassaab.com",
        "nassaabpro.com",
        "serveriran.net",
        "snapp.taxi",
        "streamg.tv",
        "taaghche.com",
        "taaghchecdn.com",
        "taranevis.com",
        "timcheh.com",
        "tipaxco.com",
        "turkeykala.com",
        "virgool.io",
    ],
}
